import fs from 'fs';
import path from 'path';

const quizzes = {
  "chap1": [
    { question: "What is the primary effect of hyperinflation on stock valuations?", options: ["Increases present value of future cash flows", "Decreases discount rates", "Increases discount rates and compresses profit margins", "Has no impact on corporate earnings"], correctAnswer: 2, explanation: "Hyperinflation leads to higher discount rates, which reduces the present value of future cash flows, compressing valuations." },
    { question: "How do rising inflation expectations generally affect existing bond prices?", options: ["Prices rise because coupons increase", "Prices fall due to the inverse relationship with yields", "Prices remain stable if held to maturity", "Prices rise because central banks buy more bonds"], correctAnswer: 1, explanation: "Inflation erodes the purchasing power of fixed coupons. As inflation rises, yields rise and existing bond prices fall." },
    { question: "Which of the following is a primary tool of Monetary Policy?", options: ["Government spending", "Corporate taxation", "Open Market Operations (OMO)", "Infrastructure subsidies"], correctAnswer: 2, explanation: "OMO is a key tool used by central banks to control the money supply." },
    { question: "What is the purpose of Contractionary Monetary Policy?", options: ["To stimulate economic growth", "To inject liquidity into the banking system", "To cool down an overheating economy and fight inflation", "To increase government deficits"], correctAnswer: 2, explanation: "Contractionary policy (hiking rates, selling bonds) is used to fight inflation." },
    { question: "Quantitative Easing (QE) is an example of which type of policy?", options: ["Contractionary Monetary Policy", "Expansionary Monetary Policy", "Contractionary Fiscal Policy", "Expansionary Fiscal Policy"], correctAnswer: 1, explanation: "QE involves the central bank buying bonds to inject liquidity, making it expansionary monetary policy." },
    { question: "What happens when a central bank lowers the Reserve Requirement?", options: ["Banks must hold more cash, reducing lending", "Banks can lend out a larger portion of their deposits, increasing money supply", "Interest rates automatically increase", "The government collects more taxes"], correctAnswer: 1, explanation: "Lowering the reserve requirement allows banks to lend more, increasing the money supply." },
    { question: "Which entity is responsible for executing Fiscal Policy in the United States?", options: ["The Federal Reserve", "The executive and legislative branches of the government", "Commercial Banks", "The Securities and Exchange Commission"], correctAnswer: 1, explanation: "Fiscal policy is driven by the government through taxation and spending." },
    { question: "What does Expansionary Fiscal Policy typically involve?", options: ["Raising taxes and cutting spending", "Cutting taxes and increasing government spending", "Hiking interest rates", "Selling government bonds"], correctAnswer: 1, explanation: "Cutting taxes and increasing spending boosts aggregate demand." },
    { question: "What is the 'Crowding-out Effect'?", options: ["When foreign investors buy too many domestic stocks", "When massive government borrowing drives up interest rates, reducing private investment", "When central banks print too much money", "When low interest rates cause a housing bubble"], correctAnswer: 1, explanation: "Government deficits require issuing bonds, soaking up capital and raising rates for the private sector." },
    { question: "If the economy is in a deep recession, what is the most likely policy mix?", options: ["Contractionary monetary and contractionary fiscal", "Expansionary monetary and contractionary fiscal", "Expansionary monetary and expansionary fiscal", "Contractionary monetary and expansionary fiscal"], correctAnswer: 2, explanation: "Both the central bank and the government will try to stimulate the economy." },
    { question: "What is a 'liquidity trap'?", options: ["When interest rates are near zero but consumers/businesses refuse to spend or invest", "When banks lend out too much money, causing a credit bubble", "When inflation rises so fast that cash loses value daily", "When the government runs out of money to borrow"], correctAnswer: 0, explanation: "In a liquidity trap, monetary policy loses its effectiveness because lowering rates further doesn't spur demand." },
    { question: "How does moderate inflation generally affect corporate earnings?", options: ["It severely compresses them", "It can support earnings if companies can pass costs to consumers", "It causes immediate bankruptcy", "It forces companies to issue more equity"], correctAnswer: 1, explanation: "Moderate inflation (around 2%) usually signifies a growing economy and allows companies pricing power." },
    { question: "Which indicator is primarily used to adjust Fiscal Policy?", options: ["S&P 500 Index", "VIX Volatility Index", "GDP and Employment figures", "Gold Prices"], correctAnswer: 2, explanation: "Governments look at real economic indicators like GDP and employment to adjust spending/taxes." },
    { question: "What is the immediate effect of the central bank selling government bonds?", options: ["Money supply increases", "Money supply decreases", "Taxes decrease", "Stock market reaches all-time highs"], correctAnswer: 1, explanation: "Selling bonds absorbs cash from the banking system, reducing the money supply." },
    { question: "Why do high-growth technology stocks suffer disproportionately when discount rates rise?", options: ["Because they have high current dividends", "Because their cash flows are expected further out in the future", "Because they rely on government subsidies", "Because they are immune to inflation"], correctAnswer: 1, explanation: "Higher discount rates severely reduce the present value of distant future cash flows." },
    { question: "What is the primary difference between Monetary and Fiscal Policy?", options: ["Monetary policy targets inflation, Fiscal policy targets stock prices", "Monetary policy is controlled by the central bank, Fiscal policy by the government", "Monetary policy only uses taxes, Fiscal policy only uses interest rates", "There is no difference"], correctAnswer: 1, explanation: "The central bank handles monetary policy; the government handles fiscal policy." },
    { question: "If inflation is at 8% and the central bank leaves rates at 0%, what is the likely outcome?", options: ["Inflation will quickly drop to 2%", "The currency will strengthen significantly", "Real interest rates are deeply negative, potentially fueling further inflation", "The crowding-out effect will occur"], correctAnswer: 2, explanation: "If nominal rates are 0% and inflation is 8%, the real rate is -8%, which is highly stimulative." },
    { question: "Which of the following is considered a Revenue Tool in Fiscal Policy?", options: ["Infrastructure spending", "Stimulus checks", "Corporate taxation", "Open Market Operations"], correctAnswer: 2, explanation: "Taxes are the primary revenue tool for governments." },
    { question: "How does highly expansionary fiscal policy during a supply-chain crisis affect the economy?", options: ["It lowers prices", "It causes massive deflation", "It drives up inflation as too much money chases too few goods", "It automatically increases the unemployment rate"], correctAnswer: 2, explanation: "Stimulating demand when supply is constrained directly causes inflation." },
    { question: "Why might a central bank hike rates even if GDP growth is slowing?", options: ["To intentionally cause a depression", "To fight stubbornly high inflation (Stagflation)", "To increase the crowding-out effect", "To help the government borrow more cheaply"], correctAnswer: 1, explanation: "If inflation is unanchored, the central bank must hike rates to fulfill its price stability mandate, even if growth suffers." }
  ],
  "chap2": [
    { question: "What is the Federal Reserve's Dual Mandate?", options: ["High stock prices and low taxes", "Stable prices and maximum employment", "Strong USD and high interest rates", "Zero inflation and zero national debt"], correctAnswer: 1, explanation: "Congress mandates the Fed to aim for stable prices (2% inflation) and maximum employment." },
    { question: "Which committee is responsible for setting the target interest rate in the US?", options: ["Federal Reserve Board of Governors", "The U.S. Treasury", "Federal Open Market Committee (FOMC)", "Securities and Exchange Commission"], correctAnswer: 2, explanation: "The FOMC sets monetary policy, including the Federal Funds Rate target." },
    { question: "How many scheduled FOMC meetings are held per year?", options: ["4", "8", "12", "24"], correctAnswer: 1, explanation: "The FOMC holds 8 regularly scheduled meetings each year." },
    { question: "What is the Federal Funds Rate?", options: ["The rate the government pays on its debt", "The rate banks charge their best corporate clients", "The target interest rate for overnight interbank lending", "The rate at which the Fed buys stocks"], correctAnswer: 2, explanation: "It is the rate at which depository institutions lend reserve balances to other depository institutions overnight." },
    { question: "Which inflation metric does the Federal Reserve primarily target?", options: ["Headline CPI", "Core PCE Price Index", "Producer Price Index (PPI)", "GDP Deflator"], correctAnswer: 1, explanation: "The Fed prefers Core PCE because it strips out volatile food and energy prices." },
    { question: "How does a higher Federal Funds Rate typically affect the Foreign Exchange market?", options: ["It weakens the USD as investors sell US assets", "It strengthens the USD by attracting yield-seeking foreign capital", "It has no impact on FX markets", "It causes the USD to be pegged to gold"], correctAnswer: 1, explanation: "Higher interest rates offer lenders a higher return relative to other countries, attracting foreign capital and raising the exchange rate." },
    { question: "What is the 'Dot Plot'?", options: ["A chart showing historical stock returns", "A summary of FOMC participants' projections for the future path of interest rates", "A map of Federal Reserve bank locations", "A technical analysis tool for trading FX"], correctAnswer: 1, explanation: "The Dot Plot shows where each Fed official expects the fed funds rate to be at the end of the next few years." },
    { question: "If the Non-Farm Payrolls (NFP) report comes in much weaker than expected, how might the market expect the Fed to react?", options: ["By aggressively hiking rates", "By ignoring the data", "By leaning Dovish and potentially cutting rates to support employment", "By raising taxes"], correctAnswer: 2, explanation: "Weak employment data threatens the 'maximum employment' mandate, prompting the Fed to loosen policy." },
    { question: "What does it mean if a Fed official's speech is described as 'Hawkish'?", options: ["They favor looser monetary policy", "They are concerned about inflation and favor tighter monetary policy (higher rates)", "They want to increase government spending", "They believe the stock market is too high"], correctAnswer: 1, explanation: "Hawks prioritize fighting inflation, usually through higher interest rates." },
    { question: "Why is the real estate market a crucial leading indicator for the Fed?", options: ["Because the Fed directly buys houses", "Because housing is highly sensitive to mortgage rates and shows how policy is transmitting to the economy", "Because real estate never loses value", "Because it is the only sector that impacts CPI"], correctAnswer: 1, explanation: "Housing requires financing; therefore, changes in interest rates immediately affect housing activity." },
    { question: "Which of the following is NOT a component of the Federal Reserve System?", options: ["The Board of Governors", "The 12 Regional Federal Reserve Banks", "The FOMC", "The Congressional Budget Office (CBO)"], correctAnswer: 3, explanation: "The CBO is a federal agency within the legislative branch, not part of the Fed." },
    { question: "How do higher interest rates generally affect gold prices?", options: ["They drive gold prices to all-time highs", "They increase the opportunity cost of holding non-yielding gold, putting downward pressure on prices", "They cause gold to pay a dividend", "They force central banks to sell all their gold reserves"], correctAnswer: 1, explanation: "Gold does not pay interest, so when risk-free rates rise, investors prefer holding bonds over gold." },
    { question: "What does a 'soft landing' refer to in the context of Fed policy?", options: ["A massive stock market crash", "Raising rates just enough to defeat inflation without causing a severe recession", "Dropping interest rates to exactly 0%", "Bailing out failing commercial banks"], correctAnswer: 1, explanation: "A soft landing means normalizing policy and bringing inflation down while avoiding a painful economic contraction." },
    { question: "Why do traders rarely trade the actual rate decision exactly when it happens?", options: ["Because trading is halted during Fed meetings", "Because the market has usually already 'priced in' the expectations leading up to the meeting", "Because the Fed keeps the decision secret for 3 weeks", "Because it is illegal"], correctAnswer: 1, explanation: "Markets are forward-looking. By the time the decision is announced, it is usually already reflected in asset prices." },
    { question: "What are FOMC Meeting Minutes?", options: ["A live broadcast of the meeting", "A short 1-page summary of the rate decision", "A detailed record of the meeting's discussions and internal disagreements, released 3 weeks later", "A list of stocks the Fed plans to buy"], correctAnswer: 2, explanation: "The minutes provide deep insight into the nuances of the FOMC's debate." },
    { question: "If inflation prints at 5% and the Fed's target is 2%, what is the most likely policy action?", options: ["Quantitative Easing", "Cutting the Federal Funds Rate", "Hiking the Federal Funds Rate", "Lowering Reserve Requirements"], correctAnswer: 2, explanation: "To bring inflation down, the Fed must implement contractionary policy (hiking rates)." },
    { question: "What is the primary risk of the Fed cutting rates too early?", options: ["Deflation", "A re-acceleration of inflation (a 'second wave')", "A soaring unemployment rate", "A collapse in the stock market"], correctAnswer: 1, explanation: "Easing financial conditions prematurely can cause inflation to surge again." },
    { question: "How does the Fed's policy transmit to corporate bond yields?", options: ["It doesn't; they are completely independent", "Corporate yields are set directly by Congress", "The Fed Funds Rate anchors the short end of the yield curve, influencing borrowing costs across all credit markets", "The Fed forces companies to issue bonds at 0%"], correctAnswer: 2, explanation: "The Fed's rate sets the risk-free baseline upon which corporate credit spreads are added." },
    { question: "Which indicator provides insight into job openings and labor turnover?", options: ["CPI", "PCE", "JOLTS", "GDP"], correctAnswer: 2, explanation: "The Job Openings and Labor Turnover Survey (JOLTS) is a key metric for labor market tightness." },
    { question: "What happens to the discount rate in a DCF valuation model when the Fed hikes rates?", options: ["It decreases", "It increases, leading to a lower present value", "It increases, leading to a higher present value", "It stays exactly the same"], correctAnswer: 1, explanation: "The risk-free rate is a core component of the discount rate. Higher discount rates lower present values." }
  ]
};

// Add empty arrays for chapters 3-8 so the app doesn't break
for (let i = 3; i <= 8; i++) {
  quizzes['chap' + i] = [];
}

const dir = path.join(process.cwd(), 'src/data');
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}
fs.writeFileSync(path.join(dir, 'snt_quizzes.json'), JSON.stringify(quizzes, null, 2));
console.log('Quizzes generated successfully.');
