import fs from 'fs';
import path from 'path';

// --- CHAPTER CONTENT ---
const chap6_sections = [
  {
    "title": "6.1 Fixed Income & Rates Research Framework",
    "body": "**6.1.1 Economic Fundamentals:** The foundation of Rates research. Analysts obsess over leading indicators that drive central bank mandates. This includes GDP growth trajectories, inflation metrics (CPI, Core PCE), and labor market health (Non-Farm Payrolls, Unemployment Rate, Wage Growth). Strong fundamentals generally drive yields higher as the market anticipates rate hikes.\n\n**6.1.2 Policies (Monetary & Fiscal):** Monetary policy (the Fed) directly controls the short end of the yield curve via the Federal Funds Rate and quantitative tightening/easing. Fiscal policy (the government) influences the long end via the supply of Treasury issuance. Massive deficit spending increases bond supply, which can drive down prices and push long-term yields higher.\n\n**6.1.3 Liquidity of the Money Market:** Examining the plumbing of the financial system. This involves monitoring the Reverse Repo facility, bank reserves, and SOFR rates to ensure there is enough cash in the system to absorb new Treasury issuance without causing a liquidity crisis."
  },
  {
    "title": "6.2 Framework of US Economic Fundamentals",
    "body": "**6.2 US Treasury Framework:** US Treasuries are the ultimate safe-haven asset and the global benchmark for risk-free rates. The core of US Treasury research is understanding how macroeconomic data surprises alter the market's expectation of the Fed's 'terminal rate' (the peak interest rate of a cycle). A hotter-than-expected CPI print immediately causes the market to price in 'higher for longer' rates, triggering a sell-off in Treasuries."
  },
  {
    "title": "6.3 Case Analysis: 2024 Retrospect and Outlook",
    "body": "**6.3.1 General Post-Pandemic Review:** Following the massive fiscal stimulus and zero-interest-rate policy of 2020-2021, inflation surged to multi-decade highs. The Fed responded with the most aggressive rate hiking cycle in modern history, taking rates from 0% to over 5%. This caused historic losses in the bond market (as yields soared, prices crashed).\n\n**6.3.2 Detailed Daily Review & 6.3.3 Short-term Outlook:** Trading desks conduct daily reviews of yield curve shifts in response to fresh data. In 2024, the narrative shifted from 'inflation panic' to 'soft landing'. The short-term outlook heavily relies on whether inflation smoothly glides down to the 2% target, allowing the Fed to execute rate cuts without the economy entering a recession."
  },
  {
    "title": "Recommended Reading",
    "body": "- [Investopedia: Economic Indicators](https://www.investopedia.com/terms/e/economic_indicator.asp)\n- [Federal Reserve: Monetary Policy Report](https://www.federalreserve.gov/monetarypolicy/mpr_default.htm)\n- [CFI: Macroeconomics](https://corporatefinanceinstitute.com/resources/economics/macroeconomics/)"
  }
];

const chap7_sections = [
  {
    "title": "7.1 Yield Curve Shapes and Historical Cases",
    "body": "**7.1.1 Normal Curve:** Slopes upward, compensating investors for tying up capital longer. \n\n**7.1.2 Steep Curve (Bull/Bear Steepener):** \n- *Case 1 (Post-Dotcom Bubble 2001-2003):* A Bull Steepener. The Fed aggressively cut short-term rates to save the economy, causing the front end of the curve to plummet while the long end remained relatively anchored.\n- *Case 2 (Taper Tantrum 2013):* A Bear Steepener. The Fed merely hinted at slowing down their bond-buying program (QE). The market panicked, and long-term yields spiked violently as investors dumped 10-year and 30-year Treasuries.\n\n**7.1.4 Inverted Curve:** \n- *Case 1 (2000 Dotcom Bubble):* The curve inverted right before the crash, signaling the market knew the Fed's high rates would break the economy.\n- *Case 2 (2022 to Soft Landing):* The curve inverted deeply as the Fed hiked rates to 5% to fight inflation, while long-term rates stayed lower because the market expected these high short rates to eventually crush growth."
  },
  {
    "title": "7.2 Drivers of Long-Term Yields (10Y/30Y)",
    "body": "**7.2.1 Real Yields:** The 'true return' on a bond. It represents the actual purchasing power an investor gains after stripping out inflation. \n\n**7.2.2 Inflation Expectations:** The 'price compensation'. Lenders demand higher nominal yields if they expect inflation to erode the value of the dollars they will be paid back with in 10 years.\n\n**7.2.3 Break-Even Inflation (BEI) & TIPS:** BEI is the market's real-time mirror for inflation expectations. It is calculated by subtracting the yield of a TIPS (Treasury Inflation-Protected Security, which pays the Real Yield) from the yield of a standard nominal Treasury bond of the same maturity.\n\n**7.2.4 & 7.2.5 Term Premium:** The 'risk compensation'. It is the extra yield investors demand to hold a long-term bond instead of just rolling over short-term bills. Therefore, **Nominal Yield = Real Yield + Inflation Expectation + Term Premium**."
  },
  {
    "title": "7.3 Case Analysis: Tariffs and Yield Movements",
    "body": "**7.3.1 & 7.3.2 Trump Tariffs (Trade War):** Tariffs act as a tax on imported goods, which inherently raises prices for domestic consumers. When sweeping tariffs were announced, the market immediately priced in a resurgence of inflation. This caused Inflation Expectations to jump. Consequently, bond investors demanded higher yields, leading to a sell-off in long-term Treasury ETFs (prices dropped as yields rose) as the market braced for 'higher for longer' Fed policy."
  },
  {
    "title": "7.4 How Hedge Funds Trade the Yield Curve",
    "body": "**7.4.1 Core Instruments:** Hedge funds rarely trade physical cash bonds because they tie up too much capital. Instead, they use Interest Rate Swaps (IRS) and Treasury Futures. These derivatives allow for massive leverage and require very little upfront margin, maximizing return on equity.\n\n**7.4.2 Hedge Fund Strategies:**\n- **7.4.2.1 Macro Strategy:** Taking massive, directional bets. If a fund believes the economy will boom and inflation will rise, they will outright short Treasury futures (betting yields will rise).\n- **7.4.2.2 Relative Value (RV):** Betting on the relationship between two points on the curve, not the absolute direction. For example, a 'Curve Steepener' trade: Buying 2-year futures and shorting 10-year futures, profiting as long as the spread between the two widens, regardless of whether overall rates go up or down.\n- **7.4.2.3 Basis Trade:** A highly leveraged, market-neutral arbitrage strategy. The fund buys the physical cash Treasury bond and simultaneously shorts the equivalent Treasury future, capturing the tiny pricing discrepancy (the basis) between the two while hedging out all directional market risk."
  },
  {
    "title": "Recommended Reading",
    "body": "- [Investopedia: Understanding the Term Premium](https://www.investopedia.com/terms/t/termpremium.asp)\n- [CFI: Fixed Income Arbitrage / Basis Trading](https://corporatefinanceinstitute.com/resources/capital-markets/fixed-income-arbitrage/)\n- [Investopedia: TIPS and Break-Even Inflation](https://www.investopedia.com/terms/b/breakeveninflation.asp)"
  }
];

// --- QUIZ QUESTIONS ---
const chap6_quizzes = [
  { question: "Which of the following is considered an Economic Fundamental when researching Rates?", options: ["The implied volatility of the S&P 500", "Gross Domestic Product (GDP) growth and Non-Farm Payrolls", "The bid-ask spread of a corporate bond", "The daily trading volume of Bitcoin"], correctAnswer: 1, explanation: "Economic fundamentals refer to macroeconomic data like GDP, employment, and inflation that drive central bank decisions." },
  { question: "How does a massive increase in Fiscal Policy (deficit spending) typically impact long-term Treasuries?", options: ["It decreases the supply of bonds, pushing yields down", "It increases the supply of bonds, which can drive prices down and push yields higher", "It forces the central bank to lower interest rates to zero", "It has absolutely no impact on the bond market"], correctAnswer: 1, explanation: "When the government runs massive deficits, it must issue more bonds. This excess supply can overwhelm demand, causing bond prices to fall and yields to rise." },
  { question: "Which indicator is primarily used by the Fed to gauge the health of the labor market?", options: ["The VIX index", "Non-Farm Payrolls (NFP) and Unemployment Rate", "Consumer Price Index (CPI)", "Retail Sales"], correctAnswer: 1, explanation: "NFP measures the number of jobs added or lost in the economy, directly tying to the Fed's maximum employment mandate." },
  { question: "What is the 'Terminal Rate'?", options: ["The interest rate charged to bankrupt companies", "The lowest interest rate during a recession", "The peak or final interest rate expected by the market during a central bank's hiking cycle", "The tax rate applied to capital gains"], correctAnswer: 2, explanation: "The terminal rate is the ultimate destination of the Fed Funds Rate before the central bank pauses or pivots." },
  { question: "If the CPI print comes in much hotter (higher) than market expectations, what is the immediate reaction in the Treasury market?", options: ["Treasury yields fall as investors buy safe havens", "Treasury yields spike as the market prices in 'higher for longer' interest rates", "The yield curve immediately flattens to zero", "Treasury prices skyrocket"], correctAnswer: 1, explanation: "Hot inflation means the Fed cannot cut rates and may have to hike further, causing existing bond prices to drop and yields to spike." },
  { question: "Why are US Treasuries considered the global benchmark for fixed income?", options: ["Because they offer the highest yields in the world", "Because they are backed by the full faith and credit of the US government and are considered free of default risk", "Because they are entirely tax-free", "Because they can be converted into physical gold"], correctAnswer: 1, explanation: "Their lack of credit risk makes them the foundation (the risk-free rate) upon which all other assets are priced." },
  { question: "What defined the 'post-pandemic' (2022-2023) bond market environment?", options: ["Zero interest rates and massive bond rallies", "The most aggressive rate hiking cycle in modern history to combat surging inflation, leading to historic bond market losses", "Deflation and negative interest rates", "A completely flat yield curve with no volatility"], correctAnswer: 1, explanation: "The Fed hiked rates aggressively from 0% to over 5%, crushing existing bond prices." },
  { question: "In the context of Rates research, what does 'Liquidity of the Money Market' refer to?", options: ["How fast a trader can sell a tech stock", "The plumbing of the financial system, ensuring enough cash (reserves/repo) exists to absorb Treasury issuance", "The amount of physical cash printed by the mint", "The dividend yield of commercial banks"], correctAnswer: 1, explanation: "It ensures the short-term funding markets function smoothly without interest rate spikes." },
  { question: "What constitutes a 'Soft Landing' scenario?", options: ["The economy enters a severe recession, forcing rates to zero", "Inflation drops to target while the economy avoids a recession and the labor market remains stable", "Inflation remains at 10% but the stock market hits all-time highs", "The central bank defaults on its debt"], correctAnswer: 1, explanation: "A soft landing is the ideal scenario where the Fed defeats inflation without breaking the economy." },
  { question: "When analyzing monetary policy, which of the following is a tool used by the Fed?", options: ["Raising corporate tax rates", "Building new infrastructure projects", "Quantitative Tightening (selling bonds to reduce money supply)", "Issuing Municipal Bonds"], correctAnswer: 2, explanation: "Quantitative Tightening (QT) is a monetary tool used to shrink the central bank's balance sheet and cool the economy." },
  { question: "Why do trading desks conduct daily reviews of yield curve shifts?", options: ["Because the SEC requires it", "To understand how fresh macroeconomic data is altering market expectations of future Fed policy", "To calculate the daily dividend payout", "To determine which stocks to short"], correctAnswer: 1, explanation: "The yield curve is a real-time pricing mechanism of future economic conditions and Fed actions." },
  { question: "If the market narrative shifts from 'inflation panic' to 'growth concerns', what happens to the yield curve?", options: ["Short-term yields spike dramatically", "Yields generally fall as the market prices in future rate cuts to stimulate growth", "The curve perfectly flattens at 10%", "Bond prices crash"], correctAnswer: 1, explanation: "Growth concerns lead to expectations of looser monetary policy, which drives yields down." },
  { question: "What is Core PCE?", options: ["A measure of government debt", "An inflation metric that strips out volatile food and energy prices, preferred by the Fed", "A measure of corporate profitability", "The interest rate banks charge each other"], correctAnswer: 1, explanation: "Core PCE is the Fed's preferred gauge to see the true, underlying trend of inflation." },
  { question: "How does strong wage growth impact Rates research?", options: ["It forces the Fed to cut rates immediately", "It is usually inflationary (services inflation), meaning the Fed may need to keep rates higher to cool demand", "It has no impact on inflation", "It causes government deficits to shrink automatically"], correctAnswer: 1, explanation: "High wage growth gives consumers more money to spend, which can keep inflation stubbornly high." },
  { question: "Which of the following represents the 'short end' of the yield curve?", options: ["30-year Treasury Bonds", "10-year Treasury Notes", "Overnight Fed Funds Rate and 3-month T-Bills", "Corporate High Yield Bonds"], correctAnswer: 2, explanation: "The short end consists of maturities under 1 year, heavily anchored by central bank policy." },
  { question: "What is a primary driver of the 'long end' of the yield curve?", options: ["Yesterday's stock market close", "Long-term inflation expectations and economic growth prospects", "The daily reverse repo rate", "The price of Bitcoin"], correctAnswer: 1, explanation: "While the Fed controls the short end, the free market dictates the long end based on decades-long outlooks." },
  { question: "If the government announces a massive new $2 Trillion spending bill without raising taxes, bond traders will likely:", options: ["Buy long-term Treasuries expecting prices to rise", "Sell long-term Treasuries, expecting yields to rise due to a flood of new bond supply", "Ignore it because fiscal policy doesn't matter", "Short the stock market"], correctAnswer: 1, explanation: "Massive unfunded spending requires massive bond issuance. High supply drives prices down and yields up." },
  { question: "What does SOFR stand for?", options: ["Secured Overnight Financing Rate", "Standard Official Federal Rate", "Simple Option Forward Ratio", "Systemic Overnight Funding Risk"], correctAnswer: 0, explanation: "SOFR is the benchmark interest rate for dollar-denominated derivatives and loans, replacing LIBOR." },
  { question: "A 'higher for longer' Fed policy implies:", options: ["Rates will be cut to zero next month", "The Fed will maintain restrictive, high interest rates for an extended period until inflation is truly dead", "The government will issue 100-year bonds", "Inflation has reached 0%"], correctAnswer: 1, explanation: "It means the Fed will not pivot to cutting rates quickly, keeping financial conditions tight." },
  { question: "Which data print is considered the most market-moving for the Rates desk on the first Friday of every month?", options: ["CPI", "Retail Sales", "Non-Farm Payrolls (NFP)", "Consumer Confidence"], correctAnswer: 2, explanation: "NFP is the premier labor market report and dictates the Fed's employment mandate." }
];

const chap7_quizzes = [
  { question: "What is the formula for the Nominal Yield of a long-term Treasury bond?", options: ["Nominal Yield = Real Yield + Term Premium", "Nominal Yield = Real Yield + Inflation Expectation + Term Premium", "Nominal Yield = Fed Funds Rate + Credit Spread", "Nominal Yield = Dividend Yield + Capital Gains"], correctAnswer: 1, explanation: "Nominal yield compensates the investor for real returns, expected inflation, and the risk of holding long-term debt (term premium)." },
  { question: "What caused the 'Taper Tantrum' of 2013?", options: ["The Fed unexpectedly hiked rates to 5%", "The Fed hinted at slowing down (tapering) its Quantitative Easing bond purchases, causing the market to panic and long-term yields to spike", "The government defaulted on its debt", "A massive deflationary spiral"], correctAnswer: 1, explanation: "The mere suggestion of reduced Fed support caused a violent Bear Steepener as investors dumped long-term bonds." },
  { question: "What is Break-Even Inflation (BEI)?", options: ["The inflation rate at which a company goes bankrupt", "The market's expected inflation rate, calculated as the difference between a Nominal Treasury yield and a TIPS yield", "The Fed's 2% target", "The difference between CPI and PCE"], correctAnswer: 1, explanation: "BEI is the exact rate of inflation where a standard Treasury and a TIPS would provide the same return." },
  { question: "How do widespread Tariffs (like the Trump trade war) generally affect the bond market?", options: ["They cause severe deflation, driving yields down", "They act as a tax on consumers, sparking inflation fears, which drives long-term yields higher", "They force the government to stop issuing bonds", "They make corporate bonds risk-free"], correctAnswer: 1, explanation: "Tariffs increase the cost of imported goods. This inflationary pressure causes bondholders to demand higher yields." },
  { question: "Why do hedge funds prefer using Interest Rate Swaps (IRS) and Futures instead of physical cash bonds?", options: ["Because physical bonds are illegal for hedge funds", "Because derivatives require much less upfront capital (margin), allowing for massive leverage", "Because derivatives pay a higher fixed coupon", "Because derivatives have zero risk"], correctAnswer: 1, explanation: "Derivatives are highly capital efficient, allowing funds to amplify their returns on small yield movements." },
  { question: "What is a 'Curve Steepener' trade in a Relative Value strategy?", options: ["Betting that all interest rates will go to zero", "Buying short-term futures and shorting long-term futures, profiting if the spread between the two widens", "Buying physical gold and shorting silver", "Arbitraging the difference between a cash bond and a future"], correctAnswer: 1, explanation: "A steepener profits when the yield curve becomes steeper, regardless of the absolute level of rates." },
  { question: "What defines a 'Basis Trade' in fixed income hedge funds?", options: ["Taking a massive directional bet on the Fed", "A market-neutral arbitrage trade exploiting tiny pricing differences between a physical cash Treasury bond and its corresponding Treasury future", "Trading bonds based purely on technical analysis", "Buying high-yield junk bonds"], correctAnswer: 1, explanation: "The basis trade uses extreme leverage to capture the tiny spread between the cash and futures markets without taking directional risk." },
  { question: "What curve shape historically precedes an economic recession?", options: ["Normal Curve", "Bull Steepener", "Inverted Curve (Short rates > Long rates)", "Flat Curve"], correctAnswer: 2, explanation: "An inverted curve indicates the market expects the central bank will be forced to slash rates in the future to rescue a broken economy." },
  { question: "What does 'Real Yield' represent?", options: ["The yield before taxes are paid", "The true purchasing power return of a bond after subtracting inflation expectations", "The yield of a junk bond", "The yield quoted on the news"], correctAnswer: 1, explanation: "Real Yield is the actual wealth increase an investor experiences, stripping out the illusion of inflation." },
  { question: "What is the 'Term Premium'?", options: ["The penalty for selling a bond early", "The extra yield investors demand as compensation for the risk of holding a long-term bond instead of rolling over short-term debt", "The commission paid to the broker", "The difference between corporate and government bonds"], correctAnswer: 1, explanation: "It compensates for duration risk and the uncertainty of holding an asset for 10 or 30 years." },
  { question: "During the 2001-2003 post-dotcom crash, what type of curve movement occurred?", options: ["Bear Flattener", "Bull Steepener (Fed cut short rates aggressively, front end plummeted)", "Bear Steepener", "Inversion"], correctAnswer: 1, explanation: "The Fed slashed rates to save the economy, causing short-term yields to crash while long-term yields remained relatively stable." },
  { question: "If a hedge fund executes a 'Macro Strategy' trade by shorting 10-year Treasury futures, what is their fundamental belief?", options: ["That inflation will drop to 0%", "That the Fed will cut rates immediately", "That the economy is running hot and long-term yields will rise (prices will fall)", "That the yield curve will invert"], correctAnswer: 2, explanation: "Shorting futures means they profit if bond prices fall. Bond prices fall when yields rise." },
  { question: "What is a TIPS bond?", options: ["A bond that pays no interest", "A Treasury Inflation-Protected Security whose principal adjusts upward with CPI inflation", "A corporate bond with a variable dividend", "A municipal bond used for infrastructure"], correctAnswer: 1, explanation: "TIPS guarantee a Real Yield by adjusting the principal based on realized inflation." },
  { question: "If the 10-year Nominal Treasury yields 4% and the 10-year TIPS yields 1.5%, what is the Break-Even Inflation rate?", options: ["5.5%", "2.5%", "4.0%", "1.5%"], correctAnswer: 1, explanation: "BEI = Nominal Yield - Real Yield. 4.0% - 1.5% = 2.5% expected inflation." },
  { question: "What happens during a 'Bear Flattener'?", options: ["Short-term rates fall faster than long rates", "Short-term rates rise faster than long-term rates, flattening the curve (usually during Fed hiking cycles)", "Long-term rates rise faster than short rates", "All rates drop to zero"], correctAnswer: 1, explanation: "Bear (yields rising) + Flattener (short end rises faster than long end). This is typical when the Fed hikes rates to fight inflation." },
  { question: "Why would an inverted yield curve eventually steepen back to normal?", options: ["Because the government defaults", "Because the Fed eventually cuts short-term rates to stimulate the economy, causing the front end to drop (Bull Steepener)", "Because inflation reaches 20%", "Because all long-term bonds mature"], correctAnswer: 1, explanation: "Recessions force the Fed to cut rates, pulling the short end down and restoring a normal upward-sloping curve." },
  { question: "In the 2022 rate hiking cycle, why did the yield curve invert so deeply?", options: ["Because long-term investors thought inflation was permanent", "Because the Fed hiked short rates to 5%, but the market kept long rates around 3.5% expecting those high rates to eventually crush the economy and inflation", "Because the Fed bought all the short-term bonds", "Because of a lack of liquidity in the money markets"], correctAnswer: 1, explanation: "The market believed the Fed's aggressive short-term hikes would successfully kill inflation and slow growth long-term." },
  { question: "Which strategy is considered 'Market Neutral'?", options: ["Macro directional short", "Naked call selling", "Basis Trade (arbitraging cash vs. futures)", "Buying a 30-year bond"], correctAnswer: 2, explanation: "A basis trade hedges out directional risk (whether rates go up or down) and only cares about the spread between the two instruments converging." },
  { question: "What is the primary risk of a Basis Trade?", options: ["Inflation rising", "The Fed cutting rates", "A severe liquidity shock or margin call that forces the fund to unwind the leveraged trade before the basis converges", "The stock market crashing"], correctAnswer: 2, explanation: "Because the margins are tiny, basis trades use massive leverage. A sudden liquidity crisis can trigger margin calls, forcing liquidation at a loss." },
  { question: "How does a Relative Value (RV) trader profit?", options: ["By correctly guessing the direction of the S&P 500", "By exploiting the changing spread or relationship between two different bonds, regardless of the overall market direction", "By holding bonds until maturity", "By trading purely on insider information"], correctAnswer: 1, explanation: "RV trading is about the relative pricing between two assets (e.g., 2yr vs 10yr), not absolute yields." }
];

// --- UPDATE SCRIPTS ---
async function run() {
  try {
    // 1. Update Curriculum
    const curriculumPath = path.join(process.cwd(), 'src/data/snt_curriculum.json');
    const curriculum = JSON.parse(fs.readFileSync(curriculumPath, 'utf-8'));
    
    const c6 = curriculum.find(c => c.id === 'chap6');
    if (c6) c6.content = { sections: chap6_sections };
    
    const c7 = curriculum.find(c => c.id === 'chap7');
    if (c7) c7.content = { sections: chap7_sections };
    
    fs.writeFileSync(curriculumPath, JSON.stringify(curriculum, null, 2));
    console.log('Curriculum updated successfully.');

    // 2. Update Quizzes
    const quizzesPath = path.join(process.cwd(), 'src/data/snt_quizzes.json');
    const quizzes = JSON.parse(fs.readFileSync(quizzesPath, 'utf-8'));
    
    quizzes.chap6 = chap6_quizzes;
    quizzes.chap7 = chap7_quizzes;
    
    fs.writeFileSync(quizzesPath, JSON.stringify(quizzes, null, 2));
    console.log('Quizzes updated successfully.');
  } catch (error) {
    console.error('Error updating data:', error);
  }
}

run();